version: "3"

services:
    elasticsearch:
        build: 
            context: .
            dockerfile: Dockerfile
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        container_name: elasticsearch
        volumes:
            - "./data:/usr/share/elasticsearch/data"
        ports:
            - "9200:9200"
        tty: true
        environment: 
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"